export const GET_ALL_FAVOURITES_ACTION = 'GET_ALL_FAVOURITES_ACTION';
export const GET_ALL_ACCOMMODATIONS_ACTION = 'GET_ALL_ACCOMMODATIONS_ACTION';
export const GET_MY_FAVOURITES_ACTION = 'GET_MY_FAVOURITES_ACTION';
export const GET_ACCOMMODATION_PROFILE = 'GET_ACCOMMODATION_PROFILE';
