export const GET_ERRORS_ACTION = 'GET_ERRORS_ACTION';
export const GET_ALL_ACCOMMODATIONS_ACTION = 'GET_ALL_ACCOMMODATIONS_ACTION';
export const GET_MY_FAVOURITES_ACTION = 'GET_MY_FAVOURITES_ACTION';
export const LOGIN_ACTION = 'LOGIN_ACTION';
export const LOGIN_CREDENTIAL_TYPING_ACTION = 'LOGIN_CREDENTIAL_TYPING_ACTION';
export const ADD_ACCOMMODATION_TO_FAVOURITES_ACTION = 'ADD_ACCOMMODATION_TO_FAVOURITES_ACTION';
